"""domain core schema

Revision ID: 20260711_02
Revises: 20260711_01
Create Date: 2026-07-11 01:12:57.681605

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260711_02"
down_revision: str | Sequence[str] | None = "20260711_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lead_outcome_reasons",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("terminal", sa.Boolean(), nullable=False),
        sa.Column("reclaimable", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "agent_employment",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "suspended",
                "handover_pending",
                "offboarded",
                name="agent_employment_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status_changed_at", sa.DateTime(), nullable=False),
        sa.Column("offboarding_started_at", sa.DateTime(), nullable=True),
        sa.Column("offboarded_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "handover_batches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_agent_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "completed",
                "cancelled",
                name="handover_batch_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("remaining_items", sa.Integer(), nullable=False),
        sa.Column("transferred_items", sa.Integer(), nullable=False),
        sa.Column("initiated_by", sa.Integer(), nullable=False),
        sa.Column("initiated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_by", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["initiated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_agent_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_handover_batches_idempotency"),
    )
    with op.batch_alter_table("handover_batches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_handover_batches_status_initiated", ["status", "initiated_at"], unique=False
        )
        batch_op.create_index(
            "uq_handover_batches_active_source",
            ["source_agent_id"],
            unique=True,
            sqlite_where=sa.text("status IN ('pending', 'in_progress')"),
            postgresql_where=sa.text("status IN ('pending', 'in_progress')"),
        )

    op.create_table(
        "agent_employment_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "active",
                "suspended",
                "handover_pending",
                "offboarded",
                name="agent_employment_event_from_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "active",
                "suspended",
                "handover_pending",
                "offboarded",
                name="agent_employment_event_to_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=True),
        sa.Column("handover_batch_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["handover_batch_id"],
            ["handover_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_employment_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_agent_employment_events_user_created", ["user_id", "created_at"], unique=False
        )

    op.create_table(
        "handover_transfers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("handover_batch_id", sa.Integer(), nullable=False),
        sa.Column("target_agent_id", sa.Integer(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "selected",
                "all_remaining",
                name="handover_transfer_mode",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "completed",
                "failed",
                name="handover_transfer_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("requested_count", sa.Integer(), nullable=False),
        sa.Column("transferred_count", sa.Integer(), nullable=False),
        sa.Column("conflict_count", sa.Integer(), nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("expected_batch_version", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["handover_batch_id"],
            ["handover_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_agent_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_handover_transfers_idempotency"),
    )
    with op.batch_alter_table("handover_transfers", schema=None) as batch_op:
        batch_op.create_index(
            "ix_handover_transfers_batch_created", ["handover_batch_id", "created_at"], unique=False
        )

    op.create_table(
        "student_assignments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("start_reason", sa.String(length=64), nullable=False),
        sa.Column("end_reason", sa.String(length=64), nullable=True),
        sa.Column("started_by", sa.Integer(), nullable=True),
        sa.Column("ended_by", sa.Integer(), nullable=True),
        sa.Column("handover_batch_id", sa.Integer(), nullable=True),
        sa.Column("previous_assignment_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ended_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["handover_batch_id"],
            ["handover_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_assignment_id"],
            ["student_assignments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["started_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("student_assignments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_student_assignments_agent_ended", ["agent_id", "ended_at"], unique=False
        )
        batch_op.create_index(
            "ix_student_assignments_student_started", ["student_id", "started_at"], unique=False
        )
        batch_op.create_index(
            "uq_student_assignments_active_student",
            ["student_id"],
            unique=True,
            sqlite_where=sa.text("ended_at IS NULL"),
            postgresql_where=sa.text("ended_at IS NULL"),
        )

    op.create_table(
        "work_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "lead_contact",
                "scheduled_follow_up",
                "home_visit",
                "campus_visit",
                "enrollment_settlement",
                "help_request",
                name="work_item_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "blocked_suspension",
                "blocked_handover",
                "completed",
                "cancelled",
                name="work_item_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("owner_agent_id", sa.Integer(), nullable=True),
        sa.Column("creator_user_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("handover_batch_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["handover_batch_id"],
            ["handover_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "source_type", "source_id", name="uq_work_items_source"),
    )
    with op.batch_alter_table("work_items", schema=None) as batch_op:
        batch_op.create_index(
            "ix_work_items_owner_status_due", ["owner_agent_id", "status", "due_at"], unique=False
        )
        batch_op.create_index(
            "ix_work_items_student_status", ["student_id", "status"], unique=False
        )

    op.create_table(
        "handover_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("handover_batch_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("source_assignment_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "transferred",
                "conflict",
                "cancelled",
                name="handover_item_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("target_agent_id", sa.Integer(), nullable=True),
        sa.Column("transfer_id", sa.Integer(), nullable=True),
        sa.Column("transferred_at", sa.DateTime(), nullable=True),
        sa.Column("conflict_code", sa.String(length=64), nullable=False),
        sa.Column("conflict_message", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["handover_batch_id"],
            ["handover_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_assignment_id"],
            ["student_assignments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"],
            ["handover_transfers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("handover_batch_id", "student_id", name="uq_handover_items_student"),
    )
    with op.batch_alter_table("handover_items", schema=None) as batch_op:
        batch_op.create_index(
            "ix_handover_items_batch_status", ["handover_batch_id", "status"], unique=False
        )

    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.add_column(sa.Column("outcome_reason_code", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.drop_column("outcome_reason_code")

    with op.batch_alter_table("handover_items", schema=None) as batch_op:
        batch_op.drop_index("ix_handover_items_batch_status")

    op.drop_table("handover_items")
    with op.batch_alter_table("work_items", schema=None) as batch_op:
        batch_op.drop_index("ix_work_items_student_status")
        batch_op.drop_index("ix_work_items_owner_status_due")

    op.drop_table("work_items")
    with op.batch_alter_table("student_assignments", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_student_assignments_active_student",
            sqlite_where=sa.text("ended_at IS NULL"),
            postgresql_where=sa.text("ended_at IS NULL"),
        )
        batch_op.drop_index("ix_student_assignments_student_started")
        batch_op.drop_index("ix_student_assignments_agent_ended")

    op.drop_table("student_assignments")
    with op.batch_alter_table("handover_transfers", schema=None) as batch_op:
        batch_op.drop_index("ix_handover_transfers_batch_created")

    op.drop_table("handover_transfers")
    with op.batch_alter_table("agent_employment_events", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_employment_events_user_created")

    op.drop_table("agent_employment_events")
    with op.batch_alter_table("handover_batches", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_handover_batches_active_source",
            sqlite_where=sa.text("status IN ('pending', 'in_progress')"),
            postgresql_where=sa.text("status IN ('pending', 'in_progress')"),
        )
        batch_op.drop_index("ix_handover_batches_status_initiated")

    op.drop_table("handover_batches")
    op.drop_table("agent_employment")
    op.drop_table("lead_outcome_reasons")
    # ### end Alembic commands ###
