"""current schema baseline

Revision ID: 20260711_01
Revises:
Create Date: 2026-07-11 00:49:12.209591

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260711_01"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("attempted_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_login_attempts_attempted_at"), ["attempted_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_login_attempts_ip"), ["ip"], unique=False)

    op.create_table(
        "system_configs",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    # These four tables are frozen legacy storage present in production but no
    # longer mapped by the runtime ORM. Keeping them here makes a fresh baseline
    # structurally compatible without reintroducing them to application code.
    op.create_table(
        "agents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("wechat", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=True),
        sa.Column("is_locked", sa.Boolean(), server_default=sa.text("0"), nullable=True),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column("invalid_reason", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("hashed_password", sa.String(length=256), nullable=False),
        sa.Column("role", sa.Enum("admin", "agent", name="userrole"), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_super_admin", sa.Boolean(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("service_regions", sa.String(length=512), nullable=False),
        sa.Column("pushplus_token", sa.String(length=64), nullable=False),
        sa.Column("page_permissions", sa.String(length=512), nullable=False),
        sa.Column("operation_permissions", sa.String(length=1024), nullable=False),
        sa.Column("last_login_device", sa.String(length=512), nullable=False),
        sa.Column("last_login_ip", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "operation_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=True),
        sa.Column("operator_name", sa.String(length=64), nullable=False),
        sa.Column("target_student_id", sa.Integer(), nullable=True),
        sa.Column("case_no", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("old_status", sa.String(length=32), nullable=True),
        sa.Column("new_status", sa.String(length=32), nullable=True),
        sa.Column("note_content", sa.Text(), nullable=True),
        sa.Column("batch_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("operation_logs", schema=None) as batch_op:
        batch_op.create_index("ix_operation_logs_action", ["action"], unique=False)
        batch_op.create_index("ix_operation_logs_batch_id", ["batch_id"], unique=False)
        batch_op.create_index(
            "ix_operation_logs_target_student_id", ["target_student_id"], unique=False
        )

    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("assigned_to", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new_lead",
                "not_contacted",
                "unassigned",
                "contacted",
                "pending_visit",
                "completed",
                "invalid",
                "enrolled",
                "rejected",
                "expired",
                "very_interested",
                "interested_add_wechat",
                "not_reached",
                "high_score",
                "not_interested",
                "no_intent",
                "child_not_want_study",
                "child_not_interested",
                name="studentstatus",
            ),
            nullable=False,
        ),
        sa.Column("status_detail", sa.String(length=64), nullable=False),
        sa.Column(
            "intent_level", sa.Enum("A", "B", "C", "none", name="intentlevel"), nullable=False
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "initial_contact",
                "interested",
                "materials_sent",
                "home_visit_pending",
                "home_visit_scheduled",
                "home_visit_completed",
                "campus_visit_pending",
                "campus_visit_scheduled",
                "campus_visit_arrived",
                "visit_scheduled",
                "visited",
                "enrolled",
                name="studentstage",
            ),
            nullable=False,
        ),
        sa.Column("join_reasons", sa.Text(), nullable=True),
        sa.Column("enrolled_at", sa.Date(), nullable=True),
        sa.Column("program", sa.String(length=128), nullable=False),
        sa.Column("deposit", sa.Float(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("guardian_name", sa.String(length=64), nullable=False),
        sa.Column("guardian_phone", sa.String(length=20), nullable=False),
        sa.Column("guardian2_name", sa.String(length=64), nullable=False),
        sa.Column("guardian2_phone", sa.String(length=20), nullable=False),
        sa.Column("school_name", sa.String(length=128), nullable=False),
        sa.Column("school_address", sa.String(length=256), nullable=False),
        sa.Column("case_no", sa.String(length=36), nullable=True),
        sa.Column("need_help", sa.Boolean(), nullable=False),
        sa.Column("expired_at", sa.Date(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column(
            "enrollment_substage",
            sa.Enum(
                "deposit_pending",
                "full_payment_pending",
                "full_payment_received",
                "registered",
                "churned",
                name="enrollmentsubstage",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_no"),
    )
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.create_index(
            "ix_students_assigned_status", ["assigned_to", "status"], unique=False
        )
        batch_op.create_index("ix_students_guardian2_phone", ["guardian2_phone"], unique=False)
        batch_op.create_index("ix_students_guardian_phone", ["guardian_phone"], unique=False)
        batch_op.create_index(batch_op.f("ix_students_region"), ["region"], unique=False)
        batch_op.create_index(batch_op.f("ix_students_school_name"), ["school_name"], unique=False)
        batch_op.create_index("ix_students_status_school", ["status", "school_name"], unique=False)

    op.create_table(
        "calls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("recording_path", sa.String(length=512), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("ai_intent", sa.String(length=8), nullable=True),
        sa.Column("ai_reasons", sa.Text(), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("ai_confidence", sa.Float(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.create_index("ix_calls_agent_id", ["agent_id"], unique=False)
        batch_op.create_index("ix_calls_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_calls_student_id", ["student_id"], unique=False)

    op.create_table(
        "dial_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("dialed_at", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "recording_state", sa.String(length=24), server_default="pending", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dial_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dial_logs_dialed_at"), ["dialed_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_dial_logs_recording_state"), ["recording_state"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_dial_logs_student_id"), ["student_id"], unique=False)

    op.create_table(
        "follow_ups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("follow_up_date", sa.DateTime(), nullable=False),
        sa.Column("follow_up_type", sa.String(length=16), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_notified", sa.Boolean(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("follow_ups", schema=None) as batch_op:
        batch_op.create_index("ix_follow_ups_agent_id", ["agent_id"], unique=False)
        batch_op.create_index("ix_follow_ups_student_id", ["student_id"], unique=False)

    op.create_table(
        "follow_up_assignments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("follow_up_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'assigned'"),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["follow_up_id"], ["follow_ups.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'pending'"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "today_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("task_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'pending'"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "home_visit_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("creator_agent_id", sa.Integer(), nullable=False),
        sa.Column("assigned_admin_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "scheduled",
                "completed",
                "cancelled",
                "postponed",
                name="homevisitstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.Enum(
                "success",
                "considering",
                "waiting_score",
                "invalid",
                "enrolled",
                "campus_visit",
                name="homevisitresult",
            ),
            nullable=True,
        ),
        sa.Column("priority", sa.String(length=8), nullable=False),
        sa.Column("student_name_snapshot", sa.String(length=64), nullable=False),
        sa.Column("guardian_phone_snapshot", sa.String(length=20), nullable=False),
        sa.Column("region_snapshot", sa.String(length=64), nullable=False),
        sa.Column("school_name_snapshot", sa.String(length=128), nullable=False),
        sa.Column("intent_program", sa.String(length=128), nullable=False),
        sa.Column("exam_score", sa.Float(), nullable=True),
        sa.Column("usual_score", sa.Float(), nullable=True),
        sa.Column("parent_intent", sa.Text(), nullable=False),
        sa.Column("student_situation", sa.Text(), nullable=False),
        sa.Column("is_wechat_added", sa.Boolean(), nullable=False),
        sa.Column("is_confirmed_with_guardian", sa.Boolean(), nullable=False),
        sa.Column("requested_visit_time", sa.DateTime(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("address", sa.String(length=256), nullable=False),
        sa.Column("postpone_reason", sa.String(length=64), nullable=False),
        sa.Column("guardian_attitude", sa.Text(), nullable=False),
        sa.Column("student_attitude", sa.Text(), nullable=False),
        sa.Column("concerns", sa.Text(), nullable=False),
        sa.Column("next_action", sa.String(length=64), nullable=False),
        sa.Column("next_follow_up_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("result_notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("home_visit_tasks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_home_visit_tasks_creator_agent_id", ["creator_agent_id"], unique=False
        )
        batch_op.create_index("ix_home_visit_tasks_region", ["region_snapshot"], unique=False)
        batch_op.create_index("ix_home_visit_tasks_scheduled_at", ["scheduled_at"], unique=False)
        batch_op.create_index("ix_home_visit_tasks_status", ["status"], unique=False)
        batch_op.create_index("ix_home_visit_tasks_student_id", ["student_id"], unique=False)

    op.create_table(
        "lead_view_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("viewer_id", sa.Integer(), nullable=False),
        sa.Column("viewed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["viewer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lead_view_logs", schema=None) as batch_op:
        batch_op.create_index("ix_lead_view_logs_student_id", ["student_id"], unique=False)

    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.create_index("ix_notes_student_id", ["student_id"], unique=False)

    op.create_table(
        "visits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("visit_type", sa.Enum("campus", "home", name="visittype"), nullable=False),
        sa.Column("scheduled_date", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "confirmed", "completed", "cancelled", name="visitstatus"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.create_index("ix_visits_agent_id", ["agent_id"], unique=False)
        batch_op.create_index("ix_visits_student_id", ["student_id"], unique=False)

    op.create_table(
        "campus_visit_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("creator_user_id", sa.Integer(), nullable=False),
        sa.Column("reception_admin_id", sa.Integer(), nullable=True),
        sa.Column("home_visit_task_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "scheduled",
                "arrived",
                "no_show",
                "rescheduled",
                "cancelled",
                "enrolled",
                name="campusvisitstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.Enum(
                "arrived",
                "no_show",
                "rescheduled",
                "cancelled",
                "enrolled",
                "considering",
                name="campusvisitresult",
            ),
            nullable=True,
        ),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("student_name_snapshot", sa.String(length=64), nullable=False),
        sa.Column("guardian_phone_snapshot", sa.String(length=20), nullable=False),
        sa.Column("region_snapshot", sa.String(length=64), nullable=False),
        sa.Column("school_name_snapshot", sa.String(length=128), nullable=False),
        sa.Column("intent_program", sa.String(length=128), nullable=False),
        sa.Column("appointment_at", sa.DateTime(), nullable=True),
        sa.Column("needs_pickup", sa.Boolean(), nullable=False),
        sa.Column("visitor_count", sa.Integer(), nullable=False),
        sa.Column("current_concerns", sa.Text(), nullable=False),
        sa.Column("reception_content", sa.Text(), nullable=False),
        sa.Column("guardian_attitude", sa.Text(), nullable=False),
        sa.Column("student_attitude", sa.Text(), nullable=False),
        sa.Column("onsite_enrolled", sa.Boolean(), nullable=False),
        sa.Column("not_enrolled_reason", sa.Text(), nullable=False),
        sa.Column("next_action", sa.String(length=64), nullable=False),
        sa.Column("next_follow_up_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("result_notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_visit_task_id"],
            ["home_visit_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reception_admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("campus_visit_tasks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_campus_visit_tasks_appointment_at", ["appointment_at"], unique=False
        )
        batch_op.create_index(
            "ix_campus_visit_tasks_creator_user_id", ["creator_user_id"], unique=False
        )
        batch_op.create_index("ix_campus_visit_tasks_region", ["region_snapshot"], unique=False)
        batch_op.create_index("ix_campus_visit_tasks_status", ["status"], unique=False)
        batch_op.create_index("ix_campus_visit_tasks_student_id", ["student_id"], unique=False)

    op.create_table(
        "enrollment_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("attributed_agent_id", sa.Integer(), nullable=False),
        sa.Column("confirmed_by_admin_id", sa.Integer(), nullable=False),
        sa.Column("first_assigned_agent_id", sa.Integer(), nullable=True),
        sa.Column("current_assigned_agent_id", sa.Integer(), nullable=True),
        sa.Column("last_effective_agent_id", sa.Integer(), nullable=True),
        sa.Column("home_visit_task_id", sa.Integer(), nullable=True),
        sa.Column("campus_visit_task_id", sa.Integer(), nullable=True),
        sa.Column("student_name_snapshot", sa.String(length=64), nullable=False),
        sa.Column("guardian_phone_snapshot", sa.String(length=20), nullable=False),
        sa.Column("region_snapshot", sa.String(length=64), nullable=False),
        sa.Column("school_name_snapshot", sa.String(length=128), nullable=False),
        sa.Column("intent_program", sa.String(length=128), nullable=False),
        sa.Column("enrolled_program", sa.String(length=128), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("phone_call", "home_visit", "campus_visit", "admin", name="enrollmentsource"),
            nullable=False,
        ),
        sa.Column(
            "attribution_method",
            sa.Enum(
                "current_agent",
                "campus_visit_creator",
                "home_visit_creator",
                "manual",
                name="attributionmethod",
            ),
            nullable=False,
        ),
        sa.Column("attribution_reason", sa.Text(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column(
            "settlement_status",
            sa.Enum("unsettled", "settled", "postponed", "disputed", name="settlementstatus"),
            nullable=False,
        ),
        sa.Column("settlement_notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attributed_agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campus_visit_task_id"],
            ["campus_visit_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by_admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_assigned_agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["first_assigned_agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_visit_task_id"],
            ["home_visit_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_effective_agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("enrollment_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_enrollment_records_attributed_agent_id", ["attributed_agent_id"], unique=False
        )
        batch_op.create_index("ix_enrollment_records_enrolled_at", ["enrolled_at"], unique=False)
        batch_op.create_index(
            "ix_enrollment_records_settlement_status", ["settlement_status"], unique=False
        )
        batch_op.create_index("ix_enrollment_records_student_id", ["student_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("today_tasks")
    op.drop_table("tasks")
    op.drop_table("follow_up_assignments")
    with op.batch_alter_table("enrollment_records", schema=None) as batch_op:
        batch_op.drop_index("ix_enrollment_records_student_id")
        batch_op.drop_index("ix_enrollment_records_settlement_status")
        batch_op.drop_index("ix_enrollment_records_enrolled_at")
        batch_op.drop_index("ix_enrollment_records_attributed_agent_id")

    op.drop_table("enrollment_records")
    with op.batch_alter_table("campus_visit_tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_campus_visit_tasks_student_id")
        batch_op.drop_index("ix_campus_visit_tasks_status")
        batch_op.drop_index("ix_campus_visit_tasks_region")
        batch_op.drop_index("ix_campus_visit_tasks_creator_user_id")
        batch_op.drop_index("ix_campus_visit_tasks_appointment_at")

    op.drop_table("campus_visit_tasks")
    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.drop_index("ix_visits_student_id")
        batch_op.drop_index("ix_visits_agent_id")

    op.drop_table("visits")
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_index("ix_notes_student_id")

    op.drop_table("notes")
    with op.batch_alter_table("lead_view_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_lead_view_logs_student_id")

    op.drop_table("lead_view_logs")
    with op.batch_alter_table("home_visit_tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_home_visit_tasks_student_id")
        batch_op.drop_index("ix_home_visit_tasks_status")
        batch_op.drop_index("ix_home_visit_tasks_scheduled_at")
        batch_op.drop_index("ix_home_visit_tasks_region")
        batch_op.drop_index("ix_home_visit_tasks_creator_agent_id")

    op.drop_table("home_visit_tasks")
    with op.batch_alter_table("follow_ups", schema=None) as batch_op:
        batch_op.drop_index("ix_follow_ups_student_id")
        batch_op.drop_index("ix_follow_ups_agent_id")

    op.drop_table("follow_ups")
    with op.batch_alter_table("dial_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dial_logs_student_id"))
        batch_op.drop_index(batch_op.f("ix_dial_logs_recording_state"))
        batch_op.drop_index(batch_op.f("ix_dial_logs_dialed_at"))

    op.drop_table("dial_logs")
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.drop_index("ix_calls_student_id")
        batch_op.drop_index("ix_calls_created_at")
        batch_op.drop_index("ix_calls_agent_id")

    op.drop_table("calls")
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.drop_index("ix_students_status_school")
        batch_op.drop_index(batch_op.f("ix_students_school_name"))
        batch_op.drop_index(batch_op.f("ix_students_region"))
        batch_op.drop_index("ix_students_guardian_phone")
        batch_op.drop_index("ix_students_guardian2_phone")
        batch_op.drop_index("ix_students_assigned_status")

    op.drop_table("students")
    with op.batch_alter_table("operation_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_operation_logs_target_student_id")
        batch_op.drop_index("ix_operation_logs_batch_id")
        batch_op.drop_index("ix_operation_logs_action")

    op.drop_table("operation_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    op.drop_table("agents")
    op.drop_table("system_configs")
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_attempts_ip"))
        batch_op.drop_index(batch_op.f("ix_login_attempts_attempted_at"))

    op.drop_table("login_attempts")
    # ### end Alembic commands ###
