DIAL_RECORDING_PENDING = "pending"
DIAL_RECORDING_COMPLETED = "completed"
DIAL_RECORDING_LEGACY_MISSING = "legacy_missing"

DIAL_RECORDING_STATES = frozenset(
    {
        DIAL_RECORDING_PENDING,
        DIAL_RECORDING_COMPLETED,
        DIAL_RECORDING_LEGACY_MISSING,
    }
)
